---
label: Project
hide_body: false
fields:
  - name: date
    type: datetime
    label: Date
    description: ""
    config:
      required: true
      date_format:
      time_format:
      display_utc:
    default: now
  - name: title
    type: text
    label: Title
    description: ""
    config:
      required: true
  - name: projectPicture
    type: file
    label: Project Picture
